### ISSUE TITLE
/sessions/:sessionId/event/start sometimes returns incorrect result. Sending undefined callback to KafkaNode 

### ISSUE THREAD

**Issue by manuel-freire** [e-ucm/rage-analytics-backend#38]
Error trace spotted in the logs:

~~~~
back_1 | TypeError: cb is not a function
back_1 |     at HighLevelProducer.createTopics (/app/node_modules/kafka-node/lib/highLevelProducer.js:101:16)
back_1 |     at createTopic (/app/lib/services/kafka.js:60:24)
back_1 |     at module.exports.executeTaks (/app/lib/sessions.js:338:36)
back_1 |     at module.exports.startSessionAnalysis (/app/lib/sessions.js:328:16)
back_1 |     at /app/lib/sessions.js:85:24
back_1 |     at _fulfilled (/app/node_modules/q/q.js:834:54)
back_1 |     at self.promiseDispatch.done (/app/node_modules/q/q.js:863:30)
back_1 |     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:796:13)
back_1 |     at /app/node_modules/q/q.js:604:44
back_1 |     at runSingle (/app/node_modules/q/q.js:137:13)
back_1 | POST /api/sessions/563ce0e0af6c564300eb77e5/event/start/ 500 4.427 ms - -
back_1 | GET /api/sessions/563ce0e0af6c564300eb77e5/results/ 304 2.140 ms - -
~~~~

Caused [here](https://github.com/SOHU-Co/kafka-node/blob/master/lib/highLevelProducer.js#L101) due to sending an empty callback from [here](https://github.com/e-ucm/rage-analytics-backend/blob/master/lib/services/kafka.js#L60).

According to kafka, the topic *was* created.

**Comment by RotaruDan** [comment]
Thanx for the log. We didn't prioritize this small bug because it only happens the first time a Teacher starts a class. The following tries it works correctly.

**Comment by manuel-freire** [comment]
Ok - verified that clicking the "open" button again actually works. This should still be fixed anyway, since it confuses users.

**Comment by RotaruDan** [comment]
Changed the title:

/sessions/:sessionId/event/start sometimes returns incorrect result (https://github.com/e-ucm/rage-analytics-backend/blob/master/lib/services/storm.js#L9)

The server can return that a session has correctly started even though the Storm topology hasn't been sent successfully which can confuse the user.
